apiVersion: v1
kind: Pod
metadata:
  name: pinchukproxylab-pod
  labels:
    app: pinchukproxylab
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      ports:
        - containerPort: 80

    - name: sidecar
      image: pinchukproxylab-sidecar:latest
      ports:
        - containerPort: 8090
      env:
        - name: PORT
          value: "8090"
        - name: LEGACY_APP_URL
          value: "http://127.0.0.1:9000"
        - name: SECURITY_CONTAINER_URL
          value: "http://127.0.0.1:8080/api/check"
        - name: PUBLIC_BASE_URL
          value: "https://company1.example"

    - name: security
      image: pinchukproxylab-security:latest
      ports:
        - containerPort: 8080

    - name: legacy
      image: pinchukproxylab-legacy:latest
      ports:
        - containerPort: 9000
        